apiVersion: v1
kind: Service
metadata:
  name: servicio-inventario
spec:
  type: NodePort
  selector:
    app: inventario-api
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30800